#!/bin/bash
set -e

echo "🧪 ORKIO v5 - ACCEPTANCE TESTS (AT-DEPLOY)"
echo "==========================================="
echo ""

# Check if RENDER_URL was provided
if [ -z "$1" ]; then
    echo "❌ Error: Render Frontend URL required"
    echo ""
    echo "Usage: ./run-acceptance-tests.sh <RENDER_FRONTEND_URL>"
    echo "Example: ./run-acceptance-tests.sh https://orkio-frontend.onrender.com"
    echo ""
    exit 1
fi

RENDER_URL=$1
echo "📍 Testing URL: $RENDER_URL"
echo ""

# AT-DEPLOY-01: Health check
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "AT-DEPLOY-01: Health Check"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Testing: GET $RENDER_URL/api/health"
echo ""

HEALTH_RESPONSE=$(curl -s -w "\nHTTP_CODE:%{http_code}" "$RENDER_URL/api/health")
HTTP_CODE=$(echo "$HEALTH_RESPONSE" | grep "HTTP_CODE" | cut -d: -f2)
HEALTH_BODY=$(echo "$HEALTH_RESPONSE" | sed '/HTTP_CODE/d')

echo "Response:"
echo "$HEALTH_BODY" | jq . 2>/dev/null || echo "$HEALTH_BODY"
echo ""
echo "HTTP Code: $HTTP_CODE"
echo ""

if echo "$HEALTH_BODY" | jq . &>/dev/null; then
    echo "✅ AT-DEPLOY-01 PASSED: Returns JSON (not HTML)"
else
    echo "❌ AT-DEPLOY-01 FAILED: Response is not valid JSON"
    exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "AT-DEPLOY-02: Agents → KB Upload"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  Manual test required:"
echo ""
echo "1. Open: $RENDER_URL/agents/default"
echo "2. Select an agent"
echo "3. Go to 'Knowledge Base' tab"
echo "4. Upload a small .txt file (1KB)"
echo ""
echo "Expected with DEBUG_UPLOAD_SHORT_CIRCUIT=true:"
echo "  - Status: completed (in seconds)"
echo "  - Logs in Railway API:"
echo "    * documents.upload.started { hasOrg:true, hasAgentId:true }"
echo "    * documents.upload.completed_short_circuit"
echo ""
read -p "Press Enter after completing this test..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "AT-DEPLOY-03: Chat Upload"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  Manual test required:"
echo ""
echo "1. Open: $RENDER_URL/chat"
echo "2. Start or select a conversation"
echo "3. Attach a small .txt file (1KB)"
echo ""
echo "Expected:"
echo "  - Badge shows: completed"
echo "  - Logs in Railway API:"
echo "    * documents.upload.started { hasConversationId:true }"
echo ""
read -p "Press Enter after completing this test..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "AT-DEPLOY-04: Ingest (Full RAG)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  This test requires disabling short-circuit mode"
echo ""
echo "Steps:"
echo "1. In Railway dashboard, set: DEBUG_UPLOAD_SHORT_CIRCUIT=false"
echo "2. Restart the Railway service"
echo "3. Upload a PDF file (1-5 MB) in Agents KB or Chat"
echo ""
echo "Expected:"
echo "  - Status: completed (may take longer)"
echo "  - If fails, check logs for: rag.parse.failed or chat.rag.failed"
echo ""
read -p "Press Enter after completing this test..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "AT-DEPLOY-05: No Unexpected Token Errors"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ If you reached this point without seeing:"
echo "   - 'Unexpected token' errors"
echo "   - 'Unable to transform' errors"
echo ""
echo "Then AT-DEPLOY-05 PASSED!"
echo ""
read -p "Press Enter to continue..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "AT-DEPLOY-06: Volume Persistence"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  This test verifies uploads persist after restart"
echo ""
echo "Steps:"
echo "1. Note a document URL from previous uploads (e.g., /uploads/...)"
echo "2. In Railway dashboard, restart the service"
echo "3. Try accessing the same document URL"
echo ""
echo "Expected:"
echo "  - Document is still accessible (not 404)"
echo ""
read -p "Press Enter after completing this test..."
echo ""

echo "==========================================="
echo "✅ ACCEPTANCE TESTS COMPLETE!"
echo "==========================================="
echo ""
echo "Summary:"
echo "  AT-DEPLOY-01: Health Check → ✅"
echo "  AT-DEPLOY-02: Agents KB Upload → Manual"
echo "  AT-DEPLOY-03: Chat Upload → Manual"
echo "  AT-DEPLOY-04: Full Ingest → Manual"
echo "  AT-DEPLOY-05: No Token Errors → ✅"
echo "  AT-DEPLOY-06: Persistence → Manual"
echo ""
echo "📋 For detailed logs, check:"
echo "   Railway API: railway logs (in server/ directory)"
echo "   Render Frontend: render logs orkio-frontend (in client/ directory)"
echo ""
